services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 2345:5432


  axonserver:
    image: axoniq/axonserver
    hostname: axon
    container_name: axon
    ports:
      - 8024:8024
      - 8124:8124

  travel-agent:
    image: mike272/travel-agent
    ports:
      - 8681:8681
    depends_on:
      - postgres
      - axonserver
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - AXON_AXONSERVER_SERVERS=axon

  hotel-service:
    image: mike272/hotel-service
    ports:
      - 8682:8682
    depends_on:
      - postgres
      - axonserver
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - AXON_AXONSERVER_SERVERS=axon

  transport-service:
    image: mike272/transport-service
    ports:
      - 8683:8683
    depends_on:
      - postgres
      - axonserver
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - AXON_AXONSERVER_SERVERS=axon

  api-gateway:
    image: mike272/api-gateway
    ports:
      - 9999:9999
    depends_on:
      - postgres
      - axonserver
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - AXON_AXONSERVER_SERVERS=axon

  saga-orchestrator:
    image: mike272/saga-orchestrator
    ports:
      - 8685:8685
    depends_on:
      - postgres
      - axonserver
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - AXON_AXONSERVER_SERVERS=axon

  rsww-client:
    image: mike272/rsww-client
    ports:
      - 2727:3000

